spring.application.name=api
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=tasks_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=app_user
spring.datasource.password=123456

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
